using Convnet.PageViewModels;
using Convnet.Properties;
using dnncore;
using System;
using System.Windows;
using System.Windows.Input;

namespace Convnet.Dialogs
{
    public partial class TrainingSchemeEditor : Window
    {
        public string Path { get; set; }
        public Model Model { get; set; }
        public TrainPageViewModel trainingPageViewModel;

        private readonly Microsoft.Win32.OpenFileDialog openFileDialog = new Microsoft.Win32.OpenFileDialog();
        private readonly Microsoft.Win32.SaveFileDialog saveFileDialog = new Microsoft.Win32.SaveFileDialog();

        public TrainingSchemeEditor()
        {
            InitializeComponent();
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            DataGridRates.ItemsSource = trainingPageViewModel.TrainRates;

            switch (Model.Optimizer)
            {
                case DNNOptimizers.SGD:
                    {
                        DataGridRates.Columns[6].Visibility = Visibility.Hidden;     // hide the Momentum field
                        DataGridRates.Columns[7].Visibility = Visibility.Visible;    // show the L2Penalty field
                    }
                    break;

                case DNNOptimizers.AdaDelta:
                case DNNOptimizers.Adam:
                case DNNOptimizers.Adamax:
                case DNNOptimizers.RMSProp:
                    {
                        DataGridRates.Columns[6].Visibility = Visibility.Visible;     // show the Momentum 
                        DataGridRates.Columns[7].Visibility = Visibility.Hidden;      // hide the L2Penalty field
                    }
                    break;

                case DNNOptimizers.AdaGrad:
                    {
                        DataGridRates.Columns[6].Visibility = Visibility.Hidden;     // hide the Momentum field
                        DataGridRates.Columns[7].Visibility = Visibility.Hidden;     // hide the L2Penalty field
                    }
                    break;

                case DNNOptimizers.NAG:
                case DNNOptimizers.SGDMomentum:
                case DNNOptimizers.RAdam:
                    {
                        DataGridRates.Columns[6].Visibility = Visibility.Visible;    // show the Momentum field
                        DataGridRates.Columns[7].Visibility = Visibility.Visible;    // show the L2Penalty field
                    }
                    break;
            }
        }

        private void DataGridRates_AutoGeneratedColumns(object sender, EventArgs e)
        {
            for (int i = 0; i < DataGridRates.Columns.Count; i++)
            {
                var name = GetColumnName(i);
                for (int j = 0; j < DataGridRates.Columns.Count; j++)
                    if (DataGridRates.Columns[j].Header.ToString().Equals(name))
                    {
                        DataGridRates.Columns[j].DisplayIndex = i;
                        break;
                    }
            }
        }

        private string GetColumnName(int index)
        {
            switch (index)
            {
                case 0:
                    return "BatchSize";
                case 1:
                    return "Cycles";
                case 2:
                    return "Epochs";
                case 3:
                    return "EpochMultiplier";
                case 4:
                    return "MaximumRate";
                case 5:
                    return "MinimumRate";
                case 6:
                    return "Momentum";
                case 7:
                    return "L2Penalty";
                case 8:
                    return "DecayFactor";
                case 9:
                    return "DecayAfterEpochs";
                case 10:
                    return "HorizontalFlip";
                case 11:
                    return "VerticalFlip";
                case 12:
                    return "ColorCast";
                case 13:
                    return "ColorAngle";
                case 14:
                    return "Dropout";
                case 15:
                    return "Cutout";
                case 16:
                    return "AutoAugment";
                case 17:
                    return "Distortion";
                case 18:
                    return "Interpolation";
                case 19:
                    return "Scaling";
                case 20:
                    return "Rotation";
                default:
                    return "";
            }
        }

        private void ButtonInsert_Click(object sender, RoutedEventArgs e)
        {
            int selectedIndex = DataGridRates.SelectedIndex;
            if (selectedIndex != -1)
            {
                trainingPageViewModel.TrainRates.Insert(selectedIndex, Settings.Default.TrainRate);
                DataGridRates.SelectedIndex = selectedIndex;
                DataGridRates.Focus();
            }
        }

        private void ButtonTrain_Click(object sender, RoutedEventArgs e)
        {
            bool stochastic = false;

            foreach (DNNTrainingRate rate in trainingPageViewModel.TrainRates)
            {
                if (rate.BatchSize == 1)
                {
                    stochastic = true;
                    break;
                }
            }

            if (Model.BatchNormalizationUsed() && stochastic)
            {
                Xceed.Wpf.Toolkit.MessageBox.Show("Your model uses batch normalization.\r\nThe batch size cannot be equal to 1 in this case.", "Warning", MessageBoxButton.OK);

                return;
            }

            DialogResult = true;
            this.Close();
        }

        private void ButtonSave_Click(object sender, RoutedEventArgs e)
        {
            saveFileDialog.InitialDirectory = Path;
            saveFileDialog.Filter = "Xml Training Scheme|*.scheme-xml";
            saveFileDialog.DefaultExt = ".scheme-xml";
            saveFileDialog.AddExtension = true;
            saveFileDialog.CreatePrompt = false;
            saveFileDialog.OverwritePrompt = true;
            saveFileDialog.ValidateNames = true;

            if (saveFileDialog.ShowDialog(this) == true)
            {
                string fileName = saveFileDialog.FileName;

                Mouse.OverrideCursor = Cursors.Wait;
                if (fileName.Contains("scheme-xml"))
                {
                    using (DNNDataSet.TrainingRatesDataTable table = new DNNDataSet.TrainingRatesDataTable())
                    {
                        table.BeginLoadData();
                        foreach (DNNTrainingRate rate in trainingPageViewModel.TrainRates)
                            table.AddTrainingRatesRow((int)rate.Optimizer, (double)rate.Beta1, (double)rate.Beta2, (double)rate.MaximumRate, (int)rate.BatchSize, (int)rate.Cycles, (int)rate.Epochs, (int)rate.EpochMultiplier, (double)rate.MinimumRate, (double)rate.L2Penalty, (double)rate.Momentum, (double)rate.DecayFactor, (int)rate.DecayAfterEpochs, rate.HorizontalFlip, rate.VerticalFlip, (double)rate.Dropout, (double)rate.Cutout, (double)rate.AutoAugment, (double)rate.ColorCast, (int)rate.ColorAngle, (double)rate.Distortion, (int)rate.Interpolation, (double)rate.Scaling, (double)rate.Rotation);
                        table.EndLoadData();
                        table.WriteXml(fileName, System.Data.XmlWriteMode.WriteSchema);
                    }
                    Mouse.OverrideCursor = null;
                    Title = "Training Scheme Editor - " + saveFileDialog.SafeFileName.Replace(".scheme-xml", "");
                    Xceed.Wpf.Toolkit.MessageBox.Show("Training scheme is saved", "Information", MessageBoxButton.OK);
                }
            }
            Mouse.OverrideCursor = null;
        }

        private void ButtonLoad_Click(object sender, RoutedEventArgs e)
        {
            openFileDialog.InitialDirectory = Path;
            openFileDialog.Filter = "Xml Training Scheme|*.scheme-xml";
            openFileDialog.Title = "Load Training Scheme";
            openFileDialog.DefaultExt = ".scheme-xml";
            openFileDialog.CheckFileExists = true;
            openFileDialog.CheckPathExists = true;
            openFileDialog.Multiselect = false;
            openFileDialog.ValidateNames = true;

            bool stop = false;
            while (!stop)
            {
                if (openFileDialog.ShowDialog(this) == true)
                {
                    Mouse.OverrideCursor = Cursors.Wait;
                    string fileName = openFileDialog.FileName;

                    if (fileName.Contains(".scheme-xml"))
                    {
                        try
                        {
                            using (DNNDataSet.TrainingRatesDataTable table = new DNNDataSet.TrainingRatesDataTable())
                            {
                                table.ReadXml(fileName);

                                trainingPageViewModel.TrainRates.Clear();

                                foreach (DNNDataSet.TrainingRatesRow row in table)
                                    trainingPageViewModel.TrainRates.Add(new DNNTrainingRate((DNNOptimizers)row.Optimizer, (float)row.Momentum, (float)row.L2Penalty, (float)row.Beta1, (float)row.Beta2, (uint)row.BatchSize, (uint)row.Cycles, (uint)row.Epochs, (uint)row.EpochMultiplier, (float)row.MaximumRate, (float)row.MinimumRate, (float)row.DecayFactor, (uint)row.DecayAfterEpochs, row.HorizontalFlip, row.VerticalFlip, (float)row.Dropout, (float)row.Cutout, (float)row.AutoAugment, (float)row.ColorCast, (uint)row.ColorAngle, (float)row.Distortion, (DNNInterpolation)row.Interpolation, (float)row.MaxScaling, (float)row.MaxRotation));
                            }

                            Mouse.OverrideCursor = null;
                            this.Title = "Training Scheme Editor - " + openFileDialog.SafeFileName.Replace(".scheme-xml", "");
                            stop = true;
                        }
                        catch (Exception)
                        {
                            Mouse.OverrideCursor = null;
                            Xceed.Wpf.Toolkit.MessageBox.Show("Wrong file format", "Choose a different file", MessageBoxButton.OK);
                        }
                    }
                    else
                    {
                        Mouse.OverrideCursor = null;
                        Xceed.Wpf.Toolkit.MessageBox.Show("Wrong file format", "Choose a different file", MessageBoxButton.OK);
                    }
                }
                else
                    stop = true;
            }
            Mouse.OverrideCursor = null;
        }
    }
}
